### ISSUE TITLE
Warning: Unknown prop `_radiumDidResolveStyles` on <div> tag.

### ISSUE THREAD

**Issue by osenvosem** [mobxjs/mobx-react-devtools#23] opened 2016-07-04 03:34 UTC
If I remove `<DevTools />` component there is no error.

![screen shot 2016-07-04 at 06 31 36](https://cloud.githubusercontent.com/assets/6762673/16550274/2676949e-41b1-11e6-876f-7b0d246d9d99.png)

**Comment by jameswyse** [comment] 2016-07-04 08:33
Seems this is a new warning in React v15.2.0, usually caused by forgetting to remove non-standard props before spreading them on a standard HTML element like `<div>`.

See related issue on Radium: https://github.com/FormidableLabs/radium/issues/759 and associated pull request: https://github.com/FormidableLabs/radium/pull/761

**Comment by osenvosem** [comment] 2016-07-04 19:14
@jameswyse ok, thanks.

**Comment by georgiik-welldone** [comment] 2016-07-10 10:20
So please, publish new version with fixes from radium. Coz published version contains old version of code.

**Comment by andykog** [comment] 2016-07-10 10:30
@georgiik-welldone, what do you mean 'old version'? mobx-react-devtools requires the latest version of radium, 0.17.1 https://github.com/mobxjs/mobx-react-devtools/blob/master/package.json#L34

**Comment by andykog** [comment] 2016-07-10 10:32
I think, we can drop radium for styles. May be I'll do it today.

**Comment by georgiik-welldone** [comment] 2016-07-10 10:38
@andykog sorry my bad, new changes from radium haven't come up yet. Can we rely on radium's master branch?

**Comment by andykog** [comment] 2016-07-10 10:43
@georgiik-welldone, npm can't rely on any github branch if there is no precompiled lib provided. Moreover, I'm not sure this bug is already fixed in master.

**Closed as completed** 2016-07-10 14:44 UTC

**Comment by andykog** [comment] 2016-07-10 15:09
Dropped radium, the warning won't appear in the next version of `mobx-react-devtools`

**Comment by mweststrate** [comment] 2016-07-11 10:04
Released as 4.2.1
